import axios from "axios";


axios.defaults.baseURL = "http://localhost"
axios.defaults.headers = { token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY3JlYXRlZEF0IjoiMDAwMS0wMS0wMVQwMDowMDowMFoiLCJ1cGRhdGVkQXQiOiIwMDAxLTAxLTAxVDAwOjAwOjAwWiIsImFjY291bnQiOiIxMzU5NDM0NzgxNyIsInRva2VuIjoiIiwiZXhwIjoxNjEzNTQwMTMwLCJpc3MiOiJibG9nX2FwaSIsIm5iZiI6MTYxMzUzODUzMH0.1DdM7h6yCC6T1ckHHnof14tiQ3zggKlIJRl2nx6YGe4' }